name: Tests

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ARM toolchain
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi 

    - name: Tests all families
      run: |
          for FAMILY in F0 F1 F2 F3 F4 F7 G0 G4 H7 L0 L1 L4 L5 U5 WB WL MP1; do
              for MODULE in fetch hal cmsis; do
                  if [[ $FAMILY == MP1 ]] && [[ $MODULE == cmsis ]]; then
                    echo "Skipping module $MODULE on family $FAMILY"
                    continue
                  fi

                  echo "Testing module $MODULE on family $FAMILY"

                  cd "$GITHUB_WORKSPACE/tests/$MODULE"
                  cmake -DTEST_FAMILIES=$FAMILY -DFETCH_ST_SOURCES=TRUE -B "build_$FAMILY" --log-level=TRACE
                  cmake --build "build_$FAMILY"  --config $BUILD_TYPE --
              done
          done
